// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://izkyjgomyghoiqgspbdy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml6a3lqZ29teWdob2lxZ3NwYmR5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM5Mjg4MjQsImV4cCI6MjA2OTUwNDgyNH0.Z72_kkbqmOma-pKwSFHWl_dYfrGEJvU6ZD3i30_y1m4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});